### ISSUE TITLE
Add 2018 resolutions data

### ISSUE THREAD

**Issue by ronaldtse** [iso-tc154/resolutions-data#3]
The resolution files are provided here:

https://github.com/iso-tc154/www.isotc154.org/issues/13

Please do it like #2. 

For @manuel489. Thanks!

**Comment by manuelfuenmayor** [comment]
Ok @ronaldtse , thank you.

**Comment by ronaldtse** [comment]
Ping @manuel489 any ETA? Thanks!

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse , I have added a first pass of three resolutions in https://github.com/iso-tc154/resolutions-data/pull/5 
(I also left some review questions for you please.)
I think I can deliver this task by the end of this week if it's ok for you (?).
Thank you!

**Comment by ronaldtse** [comment]
Thanks @manuel489 ! Of course, end of week is fine 😉 🎆

**Comment by manuelfuenmayor** [comment]
Hi Ron! I have pushed the rest of the plenaries here: https://github.com/iso-tc154/resolutions-data/pull/7
However, I published lots of questions for you as there were several cases where I wasn't sure how to approach the setting of the resolution. So, I'll be aware of your corrections!
Thank you!

**Comment by ronaldtse** [comment]
This is completed. Thanks!
