### ISSUE TITLE
Add 2015-2017 resolutions data

### ISSUE THREAD

**Issue by ronaldtse** [iso-tc154/resolutions-data#4]
The resolution files are provided here:

https://github.com/iso-tc154/www.isotc154.org/issues/13

Please do it like #2. 

For @anermina . Thanks!

**Comment by ronaldtse** [comment]
Ping @anermina any ETA? Thanks!

**Comment by anermina** [comment]
@ronaldtse Added into #6 .
Sorry for not uploading earlier, I just realized that only 2015-2017 files should have been converted... If any additional yaml should be added, please let me know.

**Comment by ronaldtse** [comment]
@anermina no worries! We will now have to do some de-duplication on #5 and #6. In any case, we will need the resolutions back to 2010.

**Comment by ronaldtse** [comment]
This is completed, thanks!
